### ISSUE TITLE
[feature] Pomodoro Cycles and Long Break timer

### ISSUE THREAD

**Issue by ferrarafer** [olimorris/tmux-pomodoro-plus#10]
Hey, how is going? I really like the plugin, you did a nice job.

After using it a couple of weeks, the feeling is like something is missing, specifically, a pomodoro cycles counter  or the name you wanna call it but if the user can't set the number of pomodoros it wanna make, the break time is useless. Why should I need a break session if it is the next pomodoro, if any, is not going to start after the break?

So, I think a pomodoros counter would be nice and also a long break session timer where, for example, after 4 pomodoros there is a long break before continue.

Thanks in advance.

**Comment by olimorris** [comment]
Glad you're enjoying it and thanks for the suggestion.

I'm reluctant to introduce any new complexity into the plugin as I think there are applications that are better suited to what you're after.
