### ISSUE TITLE
[Question] What's the status bar used in the screenshots ?

### ISSUE THREAD

**Issue by AYehia0** [olimorris/tmux-pomodoro-plus#11]
I tried to make it work with this theme `dracula/tmux` (which comes with a status bar) but it didn't show the pomo thing.
I am using the default configurations on linux.

Thanks in advance :smiley:

**Comment by olimorris** [comment]
It should be as simple as adding something like:

```sh
#[fg=$color_gray]%R#{pomodoro_status}
```

As I have done in my own configuration [here](https://github.com/olimorris/dotfiles/blob/4211bbc6bff07b69bafc77f958bd390b95b5b394/.config/tmux/conf/skin_shared.conf#L59).

**Comment by chfast** [comment]
What is the theme used in the screenshot?
