### ISSUE TITLE
Icon in status bar with <tmux-prefix> p not showing

### ISSUE THREAD

**Issue by metex** [olimorris/tmux-pomodoro-plus#12]
Context that i'm using the tmux-pomodoro-plus 
**tmux next-3.4**  
**zsh 5.8 (x86_64-ubuntu-linux-gnu)**, 

Plugin configuration in .tmux.conf
`set -g status-left "#{pomodoro_status}"
`

Case:
When i start with <tmux-prefix> p, with the function bellow

```
do_interpolation() {
	local string="$1"
	local interpolated="${string/$pomodoro_status_interpolation_string/$pomodoro_status}"
	echo "$interpolated"
}

```

`set -g status-left "#{pomodoro_status}" is not working, and by not working i meand, the icon is not showing

Possible fix:
if i replace with following function

```
do_interpolation() {
	local string="$1"
	local interpolated="$string$pomodoro_status_interpolation_string$pomodoro_status"
	echo "$interpolated"
}

```

The left icon in the status bar already appear when  <tmux-prefix> p.

**Comment by olimorris** [comment]
I'm not sure what you're asking me here. For me to modify the plugin so it works in your tmux config?

Happy to accept a PR if there's a bug in the statusline implementation.
