### ISSUE TITLE
Add seconds along with minutes MM:SS format

### ISSUE THREAD

**Issue by PezCoder** [olimorris/tmux-pomodoro-plus#13]
Hey! First of all, thank you for this, I've been looking for something like this plugin for a long & luckily stumbled upon this.

I wanted to know if it's possible to show not only the minutes but also the seconds, like in any typical pomodoro plugins (ex: https://flowapp.info/)

I would be happy to raise a PR for the same if you agree.

PS: On a separate note, I absolutely loved your tmux theme, & that's something I ended up copying with little modifications. I would highly recommend making it available through TPM, as the ones which are available are not that great. :)

**Comment by PezCoder** [comment]
I was checking the code & from the implementation perspective I wanted to know the following:
- Currently, I'm not able to find the code where we're configuring some interval on which the status line should be updated, is it interval based or is it event based on tmux?
  - If it's interval based, changing it to per second mayn't be the best way, as we're reading from the file to understand the diff

- (minor) We may want to pad zeroes in case of minutes & seconds ex: `00:30` when 30 seconds are left.

**Comment by olimorris** [comment]
Thanks very much. The tmux theme is based around the colors from my [Neovim theme](https://github.com/olimorris/onedarkpro.nvim).

Also, absolutely open for a PR on this, providing that we give the users an option to enable it. My other concern, as you rightly questioned, is that the display is dictated by `status-interval`. This is where my knowledge of much of tmux's functionality is exposed as I'm not sure if there is a nicer way to get around this other than `tmux set status-interval 1`.

**Comment by PezCoder** [comment]
Thank you for all the guidance on this, I would say this is my first legit open source contribution lol

**Comment by olimorris** [comment]
That's great to hear and what an awesome contribution it was. Thank you
