### ISSUE TITLE
Ability to lock keyboard while on break? 

### ISSUE THREAD

**Issue by dkaszews** [olimorris/tmux-pomodoro-plus#14]
Hi, I am trying out pomodoro to avoid situations where I wake up after hours of coding with a killing neck pain 😅 . Is there a way to lock keyboard while on a break? At work I'm using Wellnomics Workpace which locks keyboard and mouse to enforce breaks.

Would something like this be possible in Tmux? If not to block keyboard out right, maybe keep focusing a dummy window to make it effectively impossible to do anything. It would also be useful to have a grace period where the lock is only enabled after user stops typing for couple seconds so they can finish their sentence (again, Workpace feature).

**Comment by olimorris** [comment]
👋🏼 @dkaszews. Way out of my knowledge zone unfortunately. Really interesting concept and I wouldn't be surprised if there's a bash script lurking which could support this. Although surprised if it exists as a tmux plugin.

I used to follow the 20/20/20 rule and I had a cool native mac app that sorta enforced it but splashing a big 20 second countdown on my screen.

**Comment by dkaszews** [comment]
Understood, it was a stretch anyways. Native apps are unfortunately no-go for me, as I ssh from a bunch of different terminals.

I'll play around with it myself and create a PR if I can come up with something useful, no promises 😊

**Comment by olimorris** [comment]
Bashbunni put out a cool video a couple of weeks back with how she built a pomodoro. You could perhaps adapt her solution for your need:

https://www.youtube.com/watch?v=GfQjJBtO-8Y
