### ISSUE TITLE
How to get this to work with a theme?

### ISSUE THREAD

**Issue by hmajid2301** [olimorris/tmux-pomodoro-plus#19]
Hi :wave:,

Hi I'm pretty new to tmux and I'm trying to get this extension to work with the catppuccin theme. 
I have tried to do the following: `set -g status-left "#[fg=#000000]%R#{pomodoro_status}"`

````
# ...

## Theme settings
set -g status-left "#[fg=#000000]%R#{pomodoro_status}"
set -g @catppuccin_flavour 'frappe'
set -g @catppuccin_date_time "%H:%M"

set -g @pomodoro_notifications 'on'        # Enable desktop notifications from your terminal

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# ...
set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @plugin 'catppuccin/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
````

I can see the timer in the status bar for about 1/2 second when I reload the config. Then it disappears. I suspect this is to do with the catppuccin theme but I'm not sure (https://github.com/catppuccin/tmux/blob/main/catppuccin.tmux#L149). 
![image](https://user-images.githubusercontent.com/998807/236625554-ccc3044c-4c6f-4b33-8128-d9516ee80a6b.png)

P.S. I looked at your comment here: https://github.com/olimorris/tmux-pomodoro-plus/issues/11#issuecomment-1386665769. But I was wondering if there was a way to do it without keeping my own copy of the theme.

Any help would be greatly appreciated. Thanks!

Full tmux config: https://gitlab.com/hmajid2301/dotfiles/-/blob/tweaks/tmux/tmux.conf

**Comment by olimorris** [comment]
That is strange. I too am no Tmux expert and haven't come across this before. I'd advise removing all plugins, leaving the Pomodoro, then adding them back one by one. Maybe something is causing an overwrite

**Comment by olimorris** [comment]
Closing this but feel free to open up a discussion.

**Comment by haploeco** [comment]
I just wanted to comment that you can make this work using the custom config config instructions located here: https://github.com/catppuccin/tmux/tree/main/custom#module-template

I updated my `.tmux.conf.local` with the following:

```
set -g @catppuccin_custom_plugin_dir "$HOME/.local/share/tmux/custom"
set -g @catppuccin_status_modules_right "application session user host date_time pomodoro"
```

And I created the following script in `$HOME/.local/share/tmux/custom/pomodoro.sh` following the template/example.sh at the link above. 

```bash
show_pomodoro() {
  local index=$1
  local icon=$(get_tmux_option "@catppuccin_pomodoro_icon" "🍅")
  local color=$(get_tmux_option "@catppuccin_pomodoro_color" "$thm_green")
  local text=$(get_tmux_option "@catppuccin_pomodoro_text" "#{pomodoro_status}")

  local module=$( build_status_module "$index" "$icon" "$color" "$text" )

  echo "$module"
}
```

Of note, I have other config items set, but these are what enabled seeing `tmux-pomodoro-plus` in my `tpm` managed `catppuccin` theme.
