### ISSUE TITLE
Pomodoro refreshes everything in the "status-right"

### ISSUE THREAD

**Issue by rodhash** [olimorris/tmux-pomodoro-plus#34]
Hi, great project!

Whenever I do any action like starting or  canceling the Pomodoro I noticed it refreshes everything in my "status-right", in this quick vid I have some custom indicators that also get refreshed when I start / cancel the pomodoro.

Maybe this is the expected behavior (is it?) but I was wondering if I can get only Pomodoro to refresh and not all items on "status-right" .. any idea?

https://github.com/olimorris/tmux-pomodoro-plus/assets/29671981/9e55b957-a240-4f36-b123-4f5f1f2d03f9

**Comment by olimorris** [comment]
To my knowledge this is a limitation of Tmux and I've not been able to find a way to target a specific item in the statusline.
