### ISSUE TITLE
pomodoro_show_intervals does not work

### ISSUE THREAD

**Issue by FarsanRashid** [olimorris/tmux-pomodoro-plus#35]
Thanks for this nice plugin!

`pomodoro_show_intervals` mentioned in README does not show the intervals in status line. Seems the doc is outdated and `pomodoro_interval_display` should be used instead.

**Comment by olimorris** [comment]
Would appreciate a PR to correct this then you can be added as a contributor. Thanks for the spot

**Comment by FarsanRashid** [comment]
Here's the PR

https://github.com/olimorris/tmux-pomodoro-plus/pull/36

**Comment by olimorris** [comment]
Fantastic thank you. Now merged
