### ISSUE TITLE
Move files into home directory

### ISSUE THREAD

**Issue by arunoruto** [olimorris/tmux-pomodoro-plus#42]
I am trying to use this plugin under NixOS with home-manager, and I am getting the following error:
```text
'echo 5  > /nix/store/hrapm6574wdlhryxpzmfd1p8g3kq78xk-tmuxplugin-pomodoro-1.0.2/share/tmux-plugins/pomodoro/scripts/user_break_mins.txt' returned 1
'echo 2 > /nix/store/hrapm6574wdlhryxpzmfd1p8g3kq78xk-tmuxplugin-pomodoro-1.0.2/share/tmux-plugins/pomodoro/scripts/user_interval.txt' returned 1
'echo 5  > /nix/store/hrapm6574wdlhryxpzmfd1p8g3kq78xk-tmuxplugin-pomodoro-1.0.2/share/tmux-plugins/pomodoro/scripts/user_long_break_mins.txt' returned 1
```
I guess since nixos doesn't allow writing in the `/nix/store/*` dirs, you can't create a file there. Maybe move the files into a different folder under the user config? I guess `~/.cache/pomodoro/` could be suitable!

**Comment by olimorris** [comment]
That's a very good shout! Could you pull a PR together to test this? It should just be changing this [line](https://github.com/olimorris/tmux-pomodoro-plus/blob/226e15f3dac9a5bd6a176864c4b3b6109e673bdf/scripts/pomodoro.sh#L5C1-L5C29) and maybe creating a directory if it doesn't already exist.

**Comment by arunoruto** [comment]
I just made the needed changes, and it seems to be working.. somehow
I am unsure if it is due to me being on Nix or if there is a different issue, but I cannot see the progress in the status bar. However, I used the shortcuts, and they did make changes to the appropriate files.
