### ISSUE TITLE
Sound broken on macOS

### ISSUE THREAD

**Issue by mskelton** [olimorris/tmux-pomodoro-plus#5]
This seems to have broken sound on macOS due to these lines.

https://github.com/olimorris/tmux-pomodoro-plus/pull/2/files#diff-49376947ccc1be4101aa3ff278c29ca8d4e0809d5cc6e1e9102daf15b8e8f4bdR80-R85

It checks if the sound is `'on'` but then uses that as the sounds name but `on` is not a sound name.

_Originally posted by @mskelton in https://github.com/olimorris/tmux-pomodoro-plus/issues/2#issuecomment-1189067778_

**Comment by olimorris** [comment]
Thanks for flagging.

**Comment by mskelton** [comment]
Works great, thanks for the fast response!

**Comment by uzza1hossain** [comment]
Notification and sound did not work on Linux!

**Comment by olimorris** [comment]
@uzza1hossain can you raise a seperate issue for this and share your config?
