### ISSUE TITLE
[feature] Use a same key to toggle pomodoro

### ISSUE THREAD

**Issue by Freed-Wu** [olimorris/tmux-pomodoro-plus#9]
```tmux
set -g @pomodoro_start C-a
set -g @pomodoro_cancel C-a
```

It cannot work. How about:

```tmux
set -g @pomodoro_toggle C-a
```

? Thank you.

**Comment by olimorris** [comment]
Sorry for the delay in replying to this. A great suggestion and I've implemented this in 0002365c2b7fa2842a0dbfabe906faad40d6c9dc.

I didn't want to break mappings for everyone so I've kept the API the same.
